# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'BaiSiJoke' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod "AFNetworking"
pod "SDWebImage"
pod "SVProgressHUD"
pod 'Kingfisher'
pod 'MJRefresh'
pod "MJExtension"
pod 'Alamofire', '~> 4.4'
pod 'KYCircularProgress'
pod 'SnapKit', '~> 3.2.0'
  # Pods for BaiSiJoke

end
